// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHvE-6y6hbYyY3UXgRn2-wCnWO010mkSM',
    appId: '1:464253847772:web:993825c863b57c8bfe4c19',
    messagingSenderId: '464253847772',
    projectId: 'shoppingui-dd46a',
    authDomain: 'shoppingui-dd46a.firebaseapp.com',
    storageBucket: 'shoppingui-dd46a.appspot.com',
    measurementId: 'G-TZM11V3GY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJvROSfcP0Wp9YOmpExCF__OAEFjJr6pY',
    appId: '1:464253847772:android:119559461a7716bdfe4c19',
    messagingSenderId: '464253847772',
    projectId: 'shoppingui-dd46a',
    storageBucket: 'shoppingui-dd46a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8_lrX7iZDlbaiJQJhy2cDMT5q02sSwLs',
    appId: '1:464253847772:ios:10edc20db85ffe7ffe4c19',
    messagingSenderId: '464253847772',
    projectId: 'shoppingui-dd46a',
    storageBucket: 'shoppingui-dd46a.appspot.com',
    iosBundleId: 'com.example.shoppingui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8_lrX7iZDlbaiJQJhy2cDMT5q02sSwLs',
    appId: '1:464253847772:ios:10edc20db85ffe7ffe4c19',
    messagingSenderId: '464253847772',
    projectId: 'shoppingui-dd46a',
    storageBucket: 'shoppingui-dd46a.appspot.com',
    iosBundleId: 'com.example.shoppingui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHvE-6y6hbYyY3UXgRn2-wCnWO010mkSM',
    appId: '1:464253847772:web:a5a8226b1365bcdbfe4c19',
    messagingSenderId: '464253847772',
    projectId: 'shoppingui-dd46a',
    authDomain: 'shoppingui-dd46a.firebaseapp.com',
    storageBucket: 'shoppingui-dd46a.appspot.com',
    measurementId: 'G-0M23KG8DW6',
  );

}